/**
 * News ingestion + per-agent takes — PLAN.md 12.24, closing [G34].
 *
 * screens.md screen 23: "Only what moved your book, and what each agent did about it." So this
 * does two things the handoff's three hardcoded cards could not:
 *   1. Pulls REAL headlines from public RSS (no credential required).
 *   2. FILTERS to the user's actual holdings and strategies — a headline about an asset the user
 *      does not touch is not their briefing, it is noise.
 *
 * The agent "take" is generated by the bot runtime under the same voice contract as everything
 * else: the model writes the sentence, the app renders any number.
 */
import { query } from '../db/index.js';
import { THIS_CHAIN } from '../db/chain-scope.js';
import { speak } from '../bot/llm.js';
import { TONE_INSTRUCTIONS, type ToneId } from '../bot/tone.js';
import type { PersonaId } from '../bot/personas.js';
import { ON_SOLANA } from '../solana/clusters.js';
import { XSTOCKS } from '../venues/xstocks.js';
import { listPositions } from '../positions/index.js';

const FEEDS = [
  { url: 'https://www.coindesk.com/arc/outboundfeeds/rss/', tag: 'ON-CHAIN' },
  { url: 'https://cointelegraph.com/rss', tag: 'MACRO' },
];

/** design.md tag chip colours, matching the handoff's fixture. */
const TAG_STYLE: Record<string, { bg: string; fg: string }> = {
  STOCKS: { bg: 'rgba(91,147,255,.16)', fg: '#7FA9FF' },
  MACRO: { bg: 'rgba(91,147,255,.16)', fg: '#7FA9FF' },
  EARNINGS: { bg: 'rgba(240,190,85,.16)', fg: '#F0BE55' },
  'ON-CHAIN': { bg: 'rgba(73,227,155,.16)', fg: '#49E39B' },
};

export type Headline = { tag: string; title: string; at: number; link: string };

/** Minimal RSS extraction — no XML dependency for two well-formed feeds. */
export function parseRss(xml: string, tag: string, limit = 12): Headline[] {
  const items = xml.split(/<item[\s>]/).slice(1, limit + 1);
  const out: Headline[] = [];
  for (const item of items) {
    const title =
      /<title>\s*(?:<!\[CDATA\[)?([\s\S]*?)(?:\]\]>)?\s*<\/title>/.exec(item)?.[1]?.trim() ?? '';
    const link = /<link>\s*(?:<!\[CDATA\[)?([\s\S]*?)(?:\]\]>)?\s*<\/link>/.exec(item)?.[1]?.trim() ?? '';
    const date = /<pubDate>([\s\S]*?)<\/pubDate>/.exec(item)?.[1]?.trim();
    if (!title) continue;
    out.push({
      tag,
      title: title.replace(/&amp;/g, '&').replace(/&#\d+;/g, ''),
      at: date ? Date.parse(date) || Date.now() : Date.now(),
      link,
    });
  }
  return out;
}

export async function fetchHeadlines(): Promise<Headline[]> {
  const all: Headline[] = [];
  for (const feed of FEEDS) {
    try {
      const res = await fetch(feed.url, { headers: { accept: 'application/rss+xml, text/xml' } });
      if (!res.ok) continue;
      all.push(...parseRss(await res.text(), feed.tag));
    } catch {
      // One feed being down is not a reason to have no briefing.
    }
  }
  return all.sort((a, b) => b.at - a.at);
}

/**
 * The listed share an xStock tracks: its symbol without Backed's `x` (NVDAx → NVDA), or undefined for anything else.
 */
export function listedTicker(symbol: string): string | undefined {
  return XSTOCKS[symbol] && symbol.endsWith('x') ? symbol.slice(0, -1) : undefined;
}

/**
 * Real headlines about one listed share, each tagged with the token that tracks it (2026-09-23).
 *
 * On Solana the book is stocks, and the two feeds above are crypto news: an NVDAx holder's briefing matched nothing
 * and fell back to "Bitcoin slips under $86,000". Yahoo Finance publishes a public RSS feed per ticker, and every item
 * in it is about the ticker asked for, so the item is tagged by the request rather than guessed from its title. Yahoo
 * answers 404 to a request without a browser User-Agent, hence the header.
 */
export async function fetchStockHeadlines(symbols: string[], limitPerSymbol = 4): Promise<(Headline & { symbol: string })[]> {
  const out: (Headline & { symbol: string })[] = [];
  await Promise.all(
    symbols.map(async (symbol) => {
      const ticker = listedTicker(symbol);
      if (!ticker) return;
      try {
        const res = await fetch(
          `https://feeds.finance.yahoo.com/rss/2.0/headline?s=${encodeURIComponent(ticker)}&region=US&lang=en-US`,
          { headers: { accept: 'application/rss+xml, text/xml', 'user-agent': 'Mozilla/5.0 (compatible; xorr-briefing)' } },
        );
        if (!res.ok) return;
        for (const h of parseRss(await res.text(), 'STOCKS', limitPerSymbol)) out.push({ ...h, symbol });
      } catch {
        // One ticker's feed being down is not a reason to have no briefing.
      }
    }),
  );
  return out.sort((a, b) => b.at - a.at);
}

/** The user's actual exposure: symbols they hold, or have a strategy on. */
export async function heldSymbols(wallet: { id: string; address: string }): Promise<string[]> {
  const [strategies, positions] = await Promise.all([
    query<{ symbol: string }>(
      `SELECT DISTINCT symbol FROM strategies WHERE wallet_id=$1 AND chain = ${THIS_CHAIN} AND state IN ('live','watch','paused')`,
      [wallet.id],
    ),
    /*
     * Holdings as well as strategies (2026-09-23): a position with no strategy on it — bought by hand, or left after a
     * stop was swept — is still the user's book. Read through `listPositions`, which caps each ledger row at what the
     * wallet holds on chain, so a row the chain no longer backs (a fork rebuilt under it) is not news about "your book".
     */
    listPositions(wallet),
  ]);
  const held = positions.filter((p) => p.units > 0.000001).map((p) => p.symbol);
  return [...new Set([...strategies.map((r) => r.symbol), ...held])];
}

const NAMES: Record<string, string[]> = {
  BTC: ['bitcoin', 'btc'],
  ETH: ['ethereum', 'ether', 'eth'],
  SOL: ['solana', 'sol'],
  XRP: ['xrp', 'ripple'],
  DOGE: ['dogecoin', 'doge'],
  HYPE: ['hyperliquid'],
  AAVE: ['aave'],
  LINK: ['chainlink'],
  TON: ['toncoin', 'the open network'],
  // Pre-IPO tokens have no listed ticker to ask a feed for, so they are found by the company's name.
  'T-OpenAI': ['openai'],
  'T-SpaceX': ['spacex'],
  'T-Kalshi': ['kalshi'],
};

/** "Only what moved your book" — a headline that names nothing you hold is not your briefing. */
export function relevant(headlines: Headline[], symbols: string[]): (Headline & { symbol: string })[] {
  const out: (Headline & { symbol: string })[] = [];
  for (const h of headlines) {
    const lower = h.title.toLowerCase();
    for (const sym of symbols) {
      const needles = NAMES[sym] ?? [sym.toLowerCase()];
      if (needles.some((n) => lower.includes(n))) {
        out.push({ ...h, symbol: sym });
        break;
      }
    }
  }
  return out;
}

export function relativeTime(at: number, now = Date.now()): string {
  const mins = Math.max(0, Math.round((now - at) / 60_000));
  if (mins < 60) return `${mins}m`;
  const hours = Math.round(mins / 60);
  if (hours < 24) return `${hours}h`;
  return `${Math.round(hours / 24)}d`;
}

const AGENT_FOR: Record<string, PersonaId> = {
  BTC: 'momentum-scout',
  ETH: 'momentum-scout',
  SOL: 'yield-keeper',
  DOGE: 'momentum-scout',
  XRP: 'momentum-scout',
  HYPE: 'momentum-scout',
  AAVE: 'yield-keeper',
  LINK: 'momentum-scout',
  TON: 'yield-keeper',
};

export type BriefingCard = {
  id: string;
  tag: string;
  t: string;
  headline: string;
  /**
   * The agent's comment on this headline, or `null` when there is no model to produce one.
   *
   * Nullable rather than filled in. It used to fall back to the persona's written line, and the
   * result was three unrelated headlines each captioned "Everything is inside its limits. There is
   * nothing for me to do." — the same sentence three times, and on a wallet holding nothing it was
   * also a statement about positions that do not exist. `source` was already reported honestly and
   * the screen rendered `take` regardless, which is the shape of every fallback that reaches a
   * user: the metadata told the truth and the copy did not.
   */
  take: string | null;
  tagBg: string;
  tagFg: string;
  /**
   * Whether a model wrote `take`, or nothing did.
   *
   * Named `'fallback'` until the fallback line was deleted, at which point the value stopped
   * describing anything that exists: there is no fallback copy any more, and `take` is simply
   * `null`. Keeping the old word meant an API response in a project whose central claim is "no
   * fallback data" literally answered `"source":"fallback"` — true of nothing, and the first thing
   * a sceptic greps for.
   */
  source: 'model' | 'none';
  link: string;
};

/**
 * Which headlines make a briefing, given the book.
 *
 * With no exposure there is no "your book" to filter to, so the freshest general headlines stand in — real news, not a
 * fixture. With exposure, only headlines about it: this used to fall back to the freshest general news whenever nothing
 * matched, so a book of stocks was briefed on Bitcoin under a screen that says "Only what moved your book". An empty
 * briefing is the true answer then, and the screen says so.
 */
export function pickBriefing(
  exposure: string[],
  about: (Headline & { symbol: string })[],
  general: Headline[],
  count = 3,
): (Headline & { symbol: string })[] {
  if (exposure.length === 0) return general.slice(0, count).map((h) => ({ ...h, symbol: '' }));
  const seen = new Set<string>();
  const out: (Headline & { symbol: string })[] = [];
  // One headline per holding first, so three NVDAx stories do not crowd out the only TSLAx one.
  for (const pass of [true, false]) {
    for (const h of about) {
      if (out.length >= count) return out;
      if (seen.has(h.link || h.title)) continue;
      if (pass && out.some((o) => o.symbol === h.symbol)) continue;
      seen.add(h.link || h.title);
      out.push(h);
    }
  }
  return out;
}

export async function briefing(wallet: { id: string; address: string }, tone: ToneId = 'dry'): Promise<BriefingCard[]> {
  const symbols = await heldSymbols(wallet);
  let about: (Headline & { symbol: string })[];
  let general: Headline[];
  if (ON_SOLANA) {
    // The book is stocks: each holding's own feed, and the broad market (SPY, QQQ) for a book with nothing in it yet.
    const [own, market] = await Promise.all([fetchStockHeadlines(symbols), fetchStockHeadlines(['SPYx', 'QQQx'], 3)]);
    // A pre-IPO holding has no ticker feed; it is found by name in whatever stock news was fetched.
    const named = relevant([...own, ...market], symbols.filter((s) => !listedTicker(s)));
    about = [...own, ...named].sort((a, b) => b.at - a.at);
    general = market;
  } else {
    const headlines = await fetchHeadlines();
    about = relevant(headlines, symbols);
    general = headlines;
  }
  const cards = pickBriefing(symbols, about, general);

  const out: BriefingCard[] = [];
  for (const [i, h] of cards.entries()) {
    const persona = AGENT_FOR[h.symbol] ?? 'drawdown-guard';
    const said = await speak({
      persona,
      toneInstruction: TONE_INSTRUCTIONS[tone],
      situation: `A headline says: "${h.title}". Say in one sentence what you did or will do about the user's position, without naming any figure.`,
    });
    const style = TAG_STYLE[h.tag] ?? TAG_STYLE.MACRO!;
    out.push({
      id: `news-${i}`,
      tag: h.tag,
      t: relativeTime(h.at),
      headline: h.title,
      take: said.ok ? said.text : null,
      tagBg: style.bg,
      tagFg: style.fg,
      source: said.ok ? 'model' : 'none',
      link: h.link,
    });
  }
  return out;
}
